# Generated by Django 5.1.2 on 2024-10-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simplifiedaffiliate',
            options={'verbose_name': 'Упрощённая статистика', 'verbose_name_plural': 'Упрощённая статистика'},
        ),
        migrations.AddField(
            model_name='simplifiedaffiliate',
            name='promocode',
            field=models.CharField(default=123, max_length=10, verbose_name='Промокод'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simplifiedaffiliate',
            name='referrals_number',
            field=models.IntegerField(default=0, verbose_name='Кол-во приведённых клиентов'),
        ),
        migrations.AddField(
            model_name='simplifiedaffiliate',
            name='username',
            field=models.CharField(default=123, max_length=100, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='simplifiedaffiliate',
            unique_together={('promocode', 'username')},
        ),
    ]
