ENDPOINT_NAME_HUMAN = 'human'
ENDPOINT_NAME_GITHUB_COPILOT = 'github_copilot'
ENDPOINT_NAME_AMAZON_CODEWHISPERER = 'amazon_codewhisperer'
ENDPOINT_NAME_CHATGPT = 'chatgpt'
ENDPOINT_NAME_GIGACODE = 'gigacode'
ENDPOINT_NAME_YANDEXGPT = 'yandexgpt'

ENDPOINT_NAMES = [
    ENDPOINT_NAME_HUMAN,
    ENDPOINT_NAME_GITHUB_COPILOT,
    ENDPOINT_NAME_AMAZON_CODEWHISPERER,
    ENDPOINT_NAME_CHATGPT,
    ENDPOINT_NAME_GIGACODE,
    ENDPOINT_NAME_YANDEXGPT,
]
